### ISSUE TITLE
"Address already in use" error when running the register example with libmdns 0.7.3 - 0.7.5

### ISSUE THREAD

**Issue by maudieey** [librespot-org/libmdns#46]
When building and running [the register example](https://github.com/librespot-org/libmdns/blob/72a1eceeef45205c8dfa2d1826203b0348ca66f3/examples/register.rs), using libmdns version 0.7.3 through 0.7.5, I encounter an "Address already in use" error at this line:

```
let responder = libmdns::Responder::new().unwrap();
```

The full output is as follows:

```
myname@myhost:~/play/rust-hello$ cargo run
   Compiling rust-hello v0.1.0 (/home/myname/play/rust-hello)
    Finished dev [unoptimized + debuginfo] target(s) in 0.60s
     Running `target/debug/rust-hello`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/main.rs:6:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

However, if I change the dependency to `libmdns = "=0.7.2"` or `libmdns = "0.6"`, the error disappears.

Please let me know if there is any further information I can provide to help resolve this issue.

**Comment by willstott101** [comment]
0.7.5 was released to add a patch which fixed an issue which logged a warning about address already in use...

I was seeing the issue with IPv6: https://github.com/librespot-org/libmdns/commit/c73152513472211142595ffcfdcfb2ea13e136cb

Can you let me know what OS you're using and include the backtrace? thanks

**Comment by jasperpeeters** [comment]
I can confirm that this issue also happens with current version (0.8). Tested on Debian Bookworm + Ubuntu 22.04.4 LTS.

This only occurs if I have configured multiple ip addresses for the same interface. (But it happens also if I only pass one single ip via `libmdns::Responder::new_with_ip_list`.)

As @maudieey mentioned, with `libmdns = "=0.7.2"` this issue doesn't occur.

<details>
<summary>Backtrace running the code from _register.rs_ on my Ubuntu machine (with libmdns v0.8)
</summary>

```
➜  mdns_test git:(master) ✗ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/mdns_test`
thread 'main' panicked at src/main.rs:6:47:
called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
stack backtrace:
   0:     0x5f12ebaa1506 - std::backtrace_rs::backtrace::libunwind::trace::h6e4a662bea54ccfc
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5f12ebaa1506 - std::backtrace_rs::backtrace::trace_unsynchronized::hb42b4eb2797d9c0e
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5f12ebaa1506 - std::sys_common::backtrace::_print_fmt::h2bc261f3223f4e4d
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5f12ebaa1506 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9cca0343d66d16a8
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5f12ebac2c80 - core::fmt::rt::Argument::fmt::h8b666c45176be671
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/fmt/rt.rs:142:9
   5:     0x5f12ebac2c80 - core::fmt::write::h4311bce0ee536615
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/fmt/mod.rs:1120:17
   6:     0x5f12eba9f4bf - std::io::Write::write_fmt::h0685c51539d0a0cd
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/io/mod.rs:1846:15
   7:     0x5f12ebaa12e4 - std::sys_common::backtrace::_print::h25f19b1d64e81f86
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5f12ebaa12e4 - std::sys_common::backtrace::print::h2fb8f70628a241ed
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5f12ebaa29b7 - std::panicking::default_hook::{{closure}}::h05093fe2e3ef454d
  10:     0x5f12ebaa2719 - std::panicking::default_hook::h5ac38aa38e0086d2
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:292:9
  11:     0x5f12ebaa2e48 - std::panicking::rust_panic_with_hook::hed79743dc8b4b969
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:781:13
  12:     0x5f12ebaa2d22 - std::panicking::begin_panic_handler::{{closure}}::ha437b5d58f431abf
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:659:13
  13:     0x5f12ebaa1a06 - std::sys_common::backtrace::__rust_end_short_backtrace::hd98e82d5b39ec859
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5f12ebaa2a74 - rust_begin_unwind
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
  15:     0x5f12eb977af5 - core::panicking::panic_fmt::hc69c4d258fe11477
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
  16:     0x5f12eb978053 - core::result::unwrap_failed::hff299ec748d62aab
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1649:5
  17:     0x5f12eb9786ca - core::result::Result<T,E>::unwrap::h496d018f988cdd86
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1073:23
  18:     0x5f12eb9786ca - mdns_test::main::h8a13421e27266ed9
                               at /home/jasper/git/mdns_test/src/main.rs:6:21
  19:     0x5f12eb978a3b - core::ops::function::FnOnce::call_once::h8640b8769734fb3e
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
  20:     0x5f12eb9788ce - std::sys_common::backtrace::__rust_begin_short_backtrace::hf345942e47d4b54a
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:155:18
  21:     0x5f12eb9789e1 - std::rt::lang_start::{{closure}}::h29d10421771119e0
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/rt.rs:166:18
  22:     0x5f12eba9b581 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8c00837184d6f522
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:284:13
  23:     0x5f12eba9b581 - std::panicking::try::do_call::hfd8273c3b0a89311
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:554:40
  24:     0x5f12eba9b581 - std::panicking::try::h389092b34a7cd1de
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:518:19
  25:     0x5f12eba9b581 - std::panic::catch_unwind::hd784b6d233abd2d5
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panic.rs:142:14
  26:     0x5f12eba9b581 - std::rt::lang_start_internal::{{closure}}::h8d693c96d9aec4f8
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/rt.rs:148:48
  27:     0x5f12eba9b581 - std::panicking::try::do_call::h62b442e92648318b
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:554:40
  28:     0x5f12eba9b581 - std::panicking::try::h3dd33ffb0232e2bf
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:518:19
  29:     0x5f12eba9b581 - std::panic::catch_unwind::h388a168fe640f06a
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panic.rs:142:14
  30:     0x5f12eba9b581 - std::rt::lang_start_internal::hdaf8b62dc8f7de54
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/rt.rs:148:20
  31:     0x5f12eb9789ba - std::rt::lang_start::h799803aa829e27fa
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/rt.rs:165:17
  32:     0x5f12eb9788be - main
  33:     0x7cf3f2e29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  34:     0x7cf3f2e29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  35:     0x5f12eb978355 - _start
  36:                0x0 - <unknown>



```

</details>
